package security.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import security.core.entity.TPermission;
import security.core.entity.TPermissionExample;

public interface TPermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	long countByExample(TPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int deleteByExample(TPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int insert(TPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int insertSelective(TPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	List<TPermission> selectByExample(TPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	TPermission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TPermission record, @Param("example") TPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int updateByExample(@Param("record") TPermission record, @Param("example") TPermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int updateByPrimaryKeySelective(TPermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri Jul 06 14:29:58 CST 2018
	 */
	int updateByPrimaryKey(TPermission record);
}