package security.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import security.core.DTO.UserPrincipal;
import security.core.entity.TUserPrincipal;
import security.core.entity.TUserPrincipalExample;

public interface TUserPrincipalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	long countByExample(TUserPrincipalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int deleteByExample(TUserPrincipalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int insert(TUserPrincipal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int insertSelective(TUserPrincipal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	List<TUserPrincipal> selectByExample(TUserPrincipalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	TUserPrincipal selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TUserPrincipal record,
			@Param("example") TUserPrincipalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int updateByExample(@Param("record") TUserPrincipal record, @Param("example") TUserPrincipalExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int updateByPrimaryKeySelective(TUserPrincipal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_principal
	 * @mbg.generated  Wed Jul 18 20:42:00 CST 2018
	 */
	int updateByPrimaryKey(TUserPrincipal record);

	UserPrincipal selectUserPrincipalByUsername(String username);
}